language: java
deploy:
  provider: pages
  skip_cleanup: true
  github_token: 0c82dbcb0115c3ebbcce2c9ee79e531f48e222ef
  on:
    branch: master
env:
  global:
    secure: Sfe4ylYxRMtQzOx/MjITtK4vV5lAWW/wucUqSE0YZpzpCU1y7MoyHNthizb+cN7EsTuJwfVRPRApXbdlGVSAaruVXzJUNZFp8J6iubuB7u/zJQwmhZ5OmHAsPBXXLDWl7D0Zkv3NJeNQDNRiuwlYTwnn3GpmAJAU9PAloaZdOq/F84EfMAwhYQHsKN5KMJDWJuk4w3NiDfMv6Q3FAL+T4Rw/QCa0xp7M0pjbCkx2JXgUpYPVAXq4LcS6SDp0HG3xbqk2u7IdcDOuAj7oeM/MUyZyOC3X7svdu03m945w3ktGqHM776UXeS6fNFpBebu1mv4mJyNhBO8tdv2pyE8sp7tBtQsfodoU0RiebHJZN+zr43+eFBjuOhNXWpaGzd53uh/bearyxBYTy9cxVclYz5D2HdvpFF7UZipNvwPcrbcfi1neHvoSoRaJ+jrOeyNRTRkGgRUWC4aUUky1qzj0MUqzLTpqgbqyKjRxXsr/3fBE7hawAZ5nEg9H66OsLCV/MedSYysJdIlCeiJNqUDkXvndnEg9IxodSlZOdTGivqy+tcAEAEVJsjx1Ptc1UFDYp0QYe6tQ8AyFUzOXt9/6mtWQfUFxonWFj/JTxTftG9dYOZZmpB5WKZKcIENsyS/MNkO3UIMEfZHskZi+98rx4NVam2XI56XSf1hkGct6m7Q=
before_install:
  - chmod +x mvnw
services:
  - postgresql
matrix:
  include:
    env: DB=pgsql

script: mvn test -Dspring.profiles.active=$DB

before_script:
  - psql -c 'CREATE DATABASE oauth;' -U postgres
  - psql -c "CREATE USER dev WITH PASSWORD 'rahasia';" -U postgres
  - psql -c "ALTER DATABASE oauth OWNER TO dev;" -U postgres
  - mkdir config && cp database.travis.yml config/database.yml